### ISSUE TITLE
react_weather_app

### ISSUE THREAD

**Issue by mohammedavez125** [SR-Sunny-Raj/Hacktoberfest2022-EXCLUDED#101]
i would like to contribute my simple react weather app to this repository

**Comment by rjrishika** [comment]
could I make this weather app

**Comment by SR-Sunny-Raj** [comment]
Sorry to inform but this repository has been excluded from hacktoberfest. So inorder to make your PR count towards hacktoberfest, request you to make your contribution in this repository -> https://github.com/SR-Sunny-Raj/Hacktoberfest2022-for-all
