### ISSUE TITLE
Sorting algorithms in cpp

### ISSUE THREAD

**Issue by Bhavya-C-ai** [SR-Sunny-Raj/Hacktoberfest2022-EXCLUDED#105]

**Comment by asv02** [comment]
@SR-Sunny-Raj , i can add a very well-explained of all sorting algo,please assign it to me.

**Comment by abhijeet-crypto** [comment]
i want to work on this  please assign to me

**Comment by Harshdeep-Yadav** [comment]
give me the opportunity please

**Comment by SR-Sunny-Raj** [comment]
Sorry to inform but this repository has been excluded from hacktoberfest. So inorder to make your PR count towards hacktoberfest, request you to make your contribution in this repository -> https://github.com/SR-Sunny-Raj/Hacktoberfest2022-for-all
