### ISSUE TITLE
Linear Regression model using Python

### ISSUE THREAD

**Issue by ojhapiyush** [SR-Sunny-Raj/Hacktoberfest2022-EXCLUDED#112]
I would like to add linear regression model. Could it be assigned under hacktoberfest.

**Comment by SR-Sunny-Raj** [comment]
Sorry to inform but this repository has been excluded from hacktoberfest. So inorder to make your PR count towards hacktoberfest, request you to make your contribution in this repository -> https://github.com/SR-Sunny-Raj/Hacktoberfest2022-for-all
