### ISSUE TITLE
Dice game UI updation 

### ISSUE THREAD

**Issue by Alok214** [SR-Sunny-Raj/Hacktoberfest2022-EXCLUDED#130]
Image is not loading and button UI is not appropriate.

**Comment by SR-Sunny-Raj** [comment]
Sorry to inform but this repository has been excluded from hacktoberfest. So inorder to make your PR count towards hacktoberfest, request you to make your contribution in this repository -> https://github.com/SR-Sunny-Raj/Hacktoberfest2022-for-all
