### ISSUE TITLE
State-Dijkstra's Algorithm: A DP+ Dijkstra Algorithm 

### ISSUE THREAD

**Issue by vats101** [SR-Sunny-Raj/Hacktoberfest2022-EXCLUDED#143]
want to add the implementation of State-Dijkstra Algorithm :A DP+ Dijkstra based approach. This is under the HacktoberFest 2022.

**Comment by vats101** [comment]
please assign me this issue

**Comment by Harshdeep-Yadav** [comment]
can i do this

**Comment by SR-Sunny-Raj** [comment]
Sorry to inform but this repository has been excluded from hacktoberfest. So inorder to make your PR count towards hacktoberfest, request you to make your contribution in this repository -> https://github.com/SR-Sunny-Raj/Hacktoberfest2022-for-all
