### ISSUE TITLE
Longest Increasing Sequence 

### ISSUE THREAD

**Issue by vats101** [SR-Sunny-Raj/Hacktoberfest2022-EXCLUDED#144]
want to add the implementation of Longest Increasing Sequence :A DP based approach. This is under the HacktoberFest 2022.

**Comment by vats101** [comment]
please assign me this issue

**Comment by Harshdeep-Yadav** [comment]
assign me please

**Comment by SR-Sunny-Raj** [comment]
Sorry to inform but this repository has been excluded from hacktoberfest. So inorder to make your PR count towards hacktoberfest, request you to make your contribution in this repository -> https://github.com/SR-Sunny-Raj/Hacktoberfest2022-for-all
