### ISSUE TITLE
Add Sliding Window Algorithms 

### ISSUE THREAD

**Issue by vats101** [SR-Sunny-Raj/Hacktoberfest2022-EXCLUDED#145]
Would like to add Sliding Window based algorithms as a part of Hactoberfest 2022

**Comment by vats101** [comment]
please assign me this issue

**Comment by asv02** [comment]
@SR-Sunny-Raj, I can explain it very well with code, please assign it to me under hacktoberfest.

**Comment by SR-Sunny-Raj** [comment]
Sorry to inform but this repository has been excluded from hacktoberfest. So inorder to make your PR count towards hacktoberfest, request you to make your contribution in this repository -> https://github.com/SR-Sunny-Raj/Hacktoberfest2022-for-all
