### ISSUE TITLE
Update readme.md

### ISSUE THREAD

**Issue by BTANISHA11** [SR-Sunny-Raj/Hacktoberfest2022-EXCLUDED#147]
I WANT TO ADD SOME SECTIONS IN README.MD

1. how to make a pull request
2. how to create an issue
3. how to create a new branch
4. can you pls assign this to me @SR-Sunny-Raj

**Comment by SR-Sunny-Raj** [comment]
Sorry to inform but this repository has been excluded from hacktoberfest. So inorder to make your PR count towards hacktoberfest, request you to make your contribution in this repository -> https://github.com/SR-Sunny-Raj/Hacktoberfest2022-for-all
