### ISSUE TITLE
I will add 20 leetcode problems(15 medium 5 hard)

### ISSUE THREAD

**Issue by KoolAbhi03** [SR-Sunny-Raj/Hacktoberfest2022-EXCLUDED#149]

**Comment by SR-Sunny-Raj** [comment]
Sorry to inform but this repository has been excluded from hacktoberfest. So inorder to make your PR count towards hacktoberfest, request you to make your contribution in this repository -> https://github.com/SR-Sunny-Raj/Hacktoberfest2022-for-all
