### ISSUE TITLE
Comment Section

### ISSUE THREAD

**Issue by AryanSahoo-2003** [SR-Sunny-Raj/Hacktoberfest2022-EXCLUDED#153]
Hello! As I have seen many of my peers getting stuck at how to add comment section using php ..I want to create a sample website showing a basic comment section..
Can you assign it to me under Hactoberfest ?

**Comment by SR-Sunny-Raj** [comment]
Sorry to inform but this repository has been excluded from hacktoberfest. So inorder to make your PR count towards hacktoberfest, request you to make your contribution in this repository -> https://github.com/SR-Sunny-Raj/Hacktoberfest2022-for-all
