### ISSUE TITLE
Would like to add famous Indian coin change problem solved using Greedy Approach

### ISSUE THREAD

**Issue by hd2342-dubey** [SR-Sunny-Raj/Hacktoberfest2022-EXCLUDED#38]
Hello, I want to work over this, please assign it to me.

**Comment by SR-Sunny-Raj** [comment]
Sorry to inform but this repository has been excluded from hacktoberfest. So inorder to make your PR count towards hacktoberfest, request you to make your contribution in this repository -> https://github.com/SR-Sunny-Raj/Hacktoberfest2022-for-all
