### ISSUE TITLE
I want to add basic Graph algorithms

### ISSUE THREAD

**Issue by walter110white** [SR-Sunny-Raj/Hacktoberfest2022-EXCLUDED#58]

**Comment by asv02** [comment]
@walter110white, i can add a very well-explained code for each algorithm, please assign it to me.

**Comment by Ankita-278** [comment]
Can you pls assign me this issue?

**Comment by SR-Sunny-Raj** [comment]
Sorry to inform but this repository has been excluded from hacktoberfest. So inorder to make your PR count towards hacktoberfest, request you to make your contribution in this repository -> https://github.com/SR-Sunny-Raj/Hacktoberfest2022-for-all
