### ISSUE TITLE
Hyperlinks instead of Plain text

### ISSUE THREAD

**Issue by Vedant-Manjrekar** [SR-Sunny-Raj/Hacktoberfest2022-EXCLUDED#62]
I would like to work on this issue.
Instead of plain text in step 1's links, hyperlinks can be added to improve usability, but where is the code for the website?

<img width="1437" alt="Screenshot 2022-10-03 at 12 42 51 PM" src="https://user-images.githubusercontent.com/93585735/193520289-b9c62c1a-1b92-4aa4-8bb3-355188671f8e.png">

**Comment by yosaami** [comment]
I would like to work on this issue. I'm new to open source and looking for a beginner friendly issues. Willing to contribute. 
thanks

**Comment by SR-Sunny-Raj** [comment]
Sorry to inform but this repository has been excluded from hacktoberfest. So inorder to make your PR count towards hacktoberfest, request you to make your contribution in this repository -> https://github.com/SR-Sunny-Raj/Hacktoberfest2022-for-all
