### ISSUE TITLE
Simon game

### ISSUE THREAD

**Issue by ola-nishant** [SR-Sunny-Raj/Hacktoberfest2022-EXCLUDED#79]
I'd like to add Simon game, a web development project written in Javascript, HTML, and CSS.
It is also totally responsive and bug-free,
@SR-Sunny-Raj  please assign it to me

**Comment by Sandyy07** [comment]
Hi , Kindly please assign this issue to me .

**Comment by SR-Sunny-Raj** [comment]
Sorry to inform but this repository has been excluded from hacktoberfest. So inorder to make your PR count towards hacktoberfest, request you to make your contribution in this repository -> https://github.com/SR-Sunny-Raj/Hacktoberfest2022-for-all
