### ISSUE TITLE
Sorting the Linked list in c

### ISSUE THREAD

**Issue by Mayurishinde27** [SR-Sunny-Raj/Hacktoberfest2022-EXCLUDED#81]
Hello, I wanted to add code for sorting the Linked list. Please assign this issue to me.

**Comment by Rajnish2079** [comment]
hello please assign this issue to me. i want to contribute to this project

**Comment by Ankita-278** [comment]
Can you pls assign me this issue?

**Comment by SR-Sunny-Raj** [comment]
Sorry to inform but this repository has been excluded from hacktoberfest. So inorder to make your PR count towards hacktoberfest, request you to make your contribution in this repository -> https://github.com/SR-Sunny-Raj/Hacktoberfest2022-for-all
